trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python -m unittest discover -s tests
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'  # Aquí usa el nombre correcto de tu conexión
    repository: '$(dockerRepository)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
  displayName: 'Build and push Docker image'
